import { userProps } from "@/types/user";
import { images } from "@/constants";

export const user: userProps = {
  location: "",
  name: "Fussels lane, Colombo 06",
  profile: images.userProfile,
};

//TODO: restaurant is made of [menu in 3 categories cakes , pastries,sandwich,drinks, location  , open time ], each food is[ made of image , price  , rating ,delivery time , delivery price  , description , category ,its restaurant]
{
  /*
  restuarant : -name
  -rating
  -delivery time
  -logo
  -type of cuisine 
  -delivery price
  -location 
  -open time
  */
}

export const restaurants = [
  {
    id: 1,
    coverImage: images.coverImage,
    price: 800,
    name: "The Gourmet Kitchen",
    rating: 4.8,
    deliveryTime: "30 mins",
    logo: images.restaurant1,
    typeOfCuisine: "Italian",
    deliveryPrice: 3.99,
    location: {
      latitude: 40.712776,
      longitude: -74.005974,
      latitudeDelta: 0.0922,
      longitudeDelta: 0.0421,
      address: "123 Gourmet St, New York, NY 10001"
    },
    openTime: "10:00 AM - 11:00 PM",
    distance: "2.8km",
  },
  {
    id: 2,
    coverImage: images.coverImage,
    price: 900,
    name: "Sushi Heaven",
    rating: 4.5,
    deliveryTime: "30 mins",
    logo: images.restaurant2,
    typeOfCuisine: "Japanese",
    deliveryPrice: 2.5,
    location: {
      latitude: 34.052235,
      longitude: -118.243683,
      latitudeDelta: 0.0922,
      longitudeDelta: 0.0421,
      address: "456 Sushi Rd, Los Angeles, CA 90001"
    },
    openTime: "11:00 AM - 10:00 PM",
    distance: "2.8km",
  },
  {
    id: 3,
    coverImage: images.coverImage,
    price: 900,
    name: "Taco Fiesta",
    rating: 4.7,
    deliveryTime: "25-35 mins",
    logo: images.restaurant3,
    typeOfCuisine: "Mexican",
    deliveryPrice: 3.0,
    location: {
      latitude: 29.424122,
      longitude: -98.493628,
      latitudeDelta: 0.0922,
      longitudeDelta: 0.0421,
      address: "789 Taco Blvd, San Antonio, TX 78201"
    },
    openTime: "9:00 AM - 10:00 PM",
    distance: "2.8km",
  },
  {
    id: 4,
    coverImage: images.coverImage,
    price: 900,
    name: "Burger Barn",
    rating: 4.3,
    deliveryTime: "25 mins",
    logo: images.restaurant3,
    typeOfCuisine: "American",
    deliveryPrice: 1.99,
    location: {
      latitude: 41.878113,
      longitude: -87.629799,
      latitudeDelta: 0.0922,
      longitudeDelta: 0.0421,
      address: "321 Burger St, Chicago, IL 60601"
    },
    openTime: "11:00 AM - 12:00 AM",
    distance: "2.8km",
  },
  {
    id: 5,
    coverImage: images.coverImage,
    price: 900,
    name: "Pasta Palace",
    rating: 4.9,
    deliveryTime: "40 mins",
    logo: images.restaurant4,
    typeOfCuisine: "Italian",
    deliveryPrice: 2.99,
    location: {
      latitude: 51.507351,
      longitude: -0.127758,
      latitudeDelta: 0.0922,
      longitudeDelta: 0.0421,
      address: "654 Pasta Pl, London, UK SW1A 1AA"
    },
    openTime: "12:00 PM - 10:00 PM",
    distance: "2.8km",
  },
  {
    id: 6,
    coverImage: images.coverImage,
    price: 900,
    name: "Dragon Express",
    rating: 4.4,
    deliveryTime: "30 mins",
    logo: images.restaurant5,
    typeOfCuisine: "Chinese",
    deliveryPrice: 3.5,
    location: {
      latitude: 39.739236,
      longitude: -104.990251,
      latitudeDelta: 0.0922,
      longitudeDelta: 0.0421,
      address: "987 Dragon Ln, Denver, CO 80201"
    },
    openTime: "10:00 AM - 9:30 PM",
    distance: "2.8km",
  },
  {
    id: 7,
    coverImage: images.coverImage,
    price: 900,
    name: "Biryani House",
    rating: 4.6,
    deliveryTime: "40 mins",
    logo: images.restaurant6,
    typeOfCuisine: "Indian",
    deliveryPrice: 4.0,
    location: {
      latitude: 28.613939,
      longitude: 77.209021,
      latitudeDelta: 0.0922,
      longitudeDelta: 0.0421,
      address: "123 Biryani St, New Delhi, India 110001"
    },
    openTime: "11:00 AM - 10:00 PM",
    distance: "2.8km",
  },
  {
    id: 8,
    coverImage: images.coverImage,
    price: 900,
    name: "Kebab King",
    rating: 4.7,
    deliveryTime: "35 mins",
    logo: images.restaurant7,
    typeOfCuisine: "Middle Eastern",
    deliveryPrice: 2.0,
    location: {
      latitude: 36.778259,
      longitude: -119.417931,
      latitudeDelta: 0.0922,
      longitudeDelta: 0.0421,
      address: "234 Kebab Ave, Fresno, CA 93701"
    },
    openTime: "12:00 PM - 11:00 PM",
    distance: "2.8km",
  },
  {
    id: 9,
    coverImage: images.coverImage,
    price: 900,
    name: "Pizza Planet",
    rating: 4.8,
    deliveryTime: "30 mins",
    logo: images.restaurant8,
    typeOfCuisine: "Pizza",
    deliveryPrice: 2.99,
    location: {
      latitude: 34.052235,
      longitude: -118.243683,
      latitudeDelta: 0.0922,
      longitudeDelta: 0.0421,
      address: "567 Pizza St, Los Angeles, CA 90001"
    },
    openTime: "11:00 AM - 1:00 AM",
    distance: "2.8km",
  },
  {
    id: 10,
    coverImage: images.coverImage,
    price: 900,
    name: "BBQ Brothers",
    rating: 4.6,
    deliveryTime: "45 mins",
    logo: images.restaurant1,
    typeOfCuisine: "Barbecue",
    deliveryPrice: 5.0,
    location: {
      latitude: 39.961176,
      longitude: -82.998794,
      latitudeDelta: 0.0922,
      longitudeDelta: 0.0421,
      address: "678 BBQ Blvd, Columbus, OH 43201"
    },
    openTime: "12:00 PM - 10:00 PM",
    distance: "2.8km",
  },
  {
    id: 11,
    coverImage: images.coverImage,
    price: 900,
    name: "Pho Paradise",
    rating: 4.9,
    deliveryTime: "40 mins",
    logo: images.restaurant2,
    typeOfCuisine: "Vietnamese",
    deliveryPrice: 3.5,
    location: {
      latitude: 10.823099,
      longitude: 106.629664,
      latitudeDelta: 0.0922,
      longitudeDelta: 0.0421,
      address: "789 Pho Rd, Ho Chi Minh City, Vietnam"
    },
    openTime: "10:00 AM - 10:00 PM",
    distance: "2.8km",
  },
  {
    id: 12,
    coverImage: images.coverImage,
    price: 900,
    name: "Burger Joint",
    rating: 4.5,
    deliveryTime: "30 mins",
    logo: images.restaurant3,
    typeOfCuisine: "American",
    deliveryPrice: 1.99,
    location: {
      latitude: 37.774929,
      longitude: -122.419418,
      latitudeDelta: 0.0922,
      longitudeDelta: 0.0421,
      address: "234 Burger St, San Francisco, CA 94102"
    },
    openTime: "11:00 AM - 12:00 AM",
    distance: "2.8km",
  },
  {
    id: 13,
    coverImage: images.coverImage,
    price: 900,
    name: "Dim Sum Delight",
    rating: 4.7,
    deliveryTime: "25 mins",
    logo: images.restaurant4,
    typeOfCuisine: "Chinese",
    deliveryPrice: 3.0,
    location: {
      latitude: 39.904202,
      longitude: 116.407394,
      latitudeDelta: 0.0922,
      longitudeDelta: 0.0421,
      address: "567 Dim Sum Ave, Beijing, China 100000"
    },
    openTime: "10:00 AM - 10:00 PM",
    distance: "2.8km",
  },
  {
    id: 14,
    coverImage: images.coverImage,
    price: 900,
    name: "Ice Cream Haven",
    rating: 4.8,
    deliveryTime: "20 mins",
    logo: images.restaurant5,
    typeOfCuisine: "Dessert",
    deliveryPrice: 2.0,
    location: {
      latitude: 48.856613,
      longitude: 2.352222,
      latitudeDelta: 0.0922,
      longitudeDelta: 0.0421,
      address: "345 Ice Cream Rd, Paris, France 75001"
    },
    openTime: "12:00 PM - 11:00 PM",
    distance: "2.8km",
  },
  {
    id: 15,
    coverImage: images.coverImage,
    price: 900,
    name: "Salad Station",
    rating: 4.6,
    deliveryTime: "30 mins",
    logo: images.restaurant6,
    typeOfCuisine: "Healthy",
    deliveryPrice: 1.5,
    location: {
      latitude: 55.755825,
      longitude: 37.617298,
      latitudeDelta: 0.0922,
      longitudeDelta: 0.0421,
      address: "678 Salad Blvd, Moscow, Russia 101000"
    },
    openTime: "10:00 AM - 10:00 PM",
    distance: "2.8km",
  },
];


export const restaurantFoods = [
  {
    id: 1,
    name: "Triple Chocolate Brownie",
    smallImage: images.tripleChocolateSmall,
    coverImage: images.tripleChocolate,
    deliveryPrice: "Free",
    rating: 4.3,
    price: 650,
    restaurant_id: 1,
    category: "Cakes",
  },
  {
    id: 2,
    name: "Sweet And Spicy Pastry",
    smallImage: images.sweetAndSpicySmall,
    coverImage: images.sweetAndSpicy,
    deliveryPrice: "120",
    rating: 4.2,
    price: 400,
    restaurant_id: 1,
    category: "Pastries",
  },
  {
    id: 3,
    name: "Veggie Delight Sandwich",
    smallImage: images.veggie,
    coverImage: images.veggie,
    deliveryPrice: "Free",
    rating: 4.5,
    price: 350,
    restaurant_id: 16,
    category: "Sandwich",
  },
  {
    id: 4,
    name: "Cheese Burst Pizza",
    smallImage: images.tripleChocolateSmall,
    coverImage: images.tripleChocolate,
    deliveryPrice: "150",
    rating: 4.7,
    price: 900,
    restaurant_id: 1,
    category: "Pizza",
  },
  {
    id: 5,
    name: "Butter Chicken Roll",
    smallImage: images.sweetAndSpicySmall,
    coverImage: images.sweetAndSpicy,
    deliveryPrice: "50",
    rating: 4.4,
    price: 500,
    restaurant_id: 15,
    category: "Rolls",
  },
  {
    id: 6,
    name: "Margherita Pizza",
    smallImage: images.tripleChocolateSmall,
    coverImage: images.tripleChocolate,
    deliveryPrice: "130",
    rating: 4.6,
    price: 700,
    restaurant_id: 15,
    category: "Pizza",
  },
  {
    id: 7,
    name: "Garlic Bread",
    smallImage: images.veggie,
    coverImage: images.veggie,
    deliveryPrice: "Free",
    rating: 4.3,
    price: 250,
    restaurant_id: 2,
    category: "Sandwich",
  },
  {
    id: 8,
    name: "Choco Lava Cake",
    smallImage: images.veggie,
    coverImage: images.veggie,
    deliveryPrice: "60",
    rating: 4.8,
    price: 300,
    restaurant_id: 2,
    category: "Desserts",
  },
  {
    id: 9,
    name: "Paneer Tikka Wrap",
    smallImage: images.tripleChocolateSmall,
    coverImage: images.tripleChocolate,
    deliveryPrice: "100",
    rating: 4.5,
    price: 450,
    restaurant_id: 2,
    category: "Wraps",
  },
  {
    id: 10,
    name: "Mango Smoothie",
    smallImage: images.veggie,
    coverImage: images.veggie,
    deliveryPrice: "Free",
    rating: 4.2,
    price: 150,
    restaurant_id: 14,
    category: "Drinks",
  },
  {
    id: 11,
    name: "Chicken Nuggets",
    smallImage: images.sweetAndSpicySmall,
    coverImage: images.sweetAndSpicy,
    deliveryPrice: "70",
    rating: 4.4,
    price: 400,
    restaurant_id: 14,
    category: "Indian",
  },
  {
    id: 12,
    name: "Crispy Veg Burger",
    smallImage: images.tripleChocolateSmall,
    coverImage: images.tripleChocolate,
    deliveryPrice: "90",
    rating: 4.3,
    price: 200,
    restaurant_id: 3,
    category: "Burgers",
  },
  {
    id: 13,
    name: "Strawberry Milkshake",
    smallImage: images.tripleChocolateSmall,
    coverImage: images.tripleChocolate,
    deliveryPrice: "60",
    rating: 4.1,
    price: 180,
    restaurant_id: 3,
    category: "Milkshake",
  },
  {
    id: 14,
    name: "Egg Fried Rice",
    smallImage: images.veggie,
    coverImage: images.veggie,
    deliveryPrice: "110",
    rating: 4.6,
    price: 550,
    restaurant_id: 3,
    category: "Indian",
  },
  {
    id: 15,
    name: "Tandoori Chicken",
    smallImage: images.sweetAndSpicySmall,
    coverImage: images.sweetAndSpicy,
    deliveryPrice: "Free",
    rating: 4.7,
    price: 650,
    restaurant_id: 13,
    category: "Indian",
  },
  {
    id: 16,
    name: "Paneer Butter Masala",
    smallImage: images.tripleChocolateSmall,
    coverImage: images.tripleChocolate,
    deliveryPrice: "4",
    rating: 4.5,
    price: 500,
    restaurant_id: 13,
    category: "Indian",
  },
  {
    id: 17,
    name: "Cold Coffee",
    smallImage: images.veggie,
    coverImage: images.veggie,
    deliveryPrice: "Free",
    rating: 4.0,
    price: 120,
    restaurant_id: 4,
    category: "Coffee",
  },
  {
    id: 18,
    name: "Pepperoni Pizza",
    smallImage: images.veggie,
    coverImage: images.veggie,
    deliveryPrice: "160",
    rating: 4.6,
    price: 950,
    restaurant_id: 4,
    category: "Pizza",
  },
  {
    id: 19,
    name: "Vegetable Samosa",
    smallImage: images.sweetAndSpicySmall,
    coverImage: images.sweetAndSpicy,
    deliveryPrice: "Free",
    rating: 4.3,
    price: 100,
    restaurant_id: 4,
    category: "Indian",
  },
  {
    id: 20,
    name: "Mutton Biryani",
    smallImage: images.tripleChocolateSmall,
    coverImage: images.tripleChocolate,
    deliveryPrice: "140",
    rating: 4.7,
    price: 800,
    restaurant_id: 12,
    category: "Biryani",
  },
  {
    id: 21,
    name: "Pineapple Pastry",
    smallImage: images.veggie,
    coverImage: images.veggie,
    deliveryPrice: "70",
    rating: 4.2,
    price: 200,
    restaurant_id: 12,
    category: "Pastries",
  },
  {
    id: 22,
    name: "Chicken Caesar Wrap",
    smallImage: images.tripleChocolateSmall,
    coverImage: images.tripleChocolate,
    deliveryPrice: "90",
    rating: 4.6,
    price: 450,
    restaurant_id: 5,
    category: "Wraps",
  },
  {
    id: 23,
    name: "Iced Latte",
    smallImage: images.veggie,
    coverImage: images.veggie,
    deliveryPrice: "Free",
    rating: 4.0,
    price: 200,
    restaurant_id: 5,
    category: "Coffee",
  },
  {
    id: 24,
    name: "Blueberry Muffin",
    smallImage: images.sweetAndSpicySmall,
    coverImage: images.sweetAndSpicy,
    deliveryPrice: "40",
    rating: 4.4,
    price: 180,
    restaurant_id: 5,
    category: "Cakes",
  },
  {
    id: 25,
    name: "Butter Garlic Naan",
    smallImage: images.tripleChocolateSmall,
    coverImage: images.tripleChocolate,
    deliveryPrice: "80",
    rating: 4.5,
    price: 100,
    restaurant_id: 11,
    category: "Indian",
  },
  {
    id: 26,
    name: "Spaghetti Bolognese",
    smallImage: images.veggie,
    coverImage: images.veggie,
    deliveryPrice: "120",
    rating: 4.6,
    price: 650,
    restaurant_id: 11,
    category: "Indian",
  },
  {
    id: 27,
    name: "Chicken Seekh Kebab",
    smallImage: images.tripleChocolateSmall,
    coverImage: images.tripleChocolate,
    deliveryPrice: "Free",
    rating: 4.5,
    price: 350,
    restaurant_id: 6,
    category: "Indian",
  },
  {
    id: 28,
    name: "Oreo Milkshake",
    smallImage: images.veggie,
    coverImage: images.veggie,
    deliveryPrice: "60",
    rating: 4.7,
    price: 250,
    restaurant_id: 6,
    category: "Milkshake",
  },
  {
    id: 29,
    name: "Espresso Shot",
    smallImage: images.tripleChocolateSmall,
    coverImage: images.tripleChocolate,
    deliveryPrice: "50",
    rating: 4.1,
    price: 80,
    restaurant_id: 6,
    category: "Coffee",
  },
  {
    id: 30,
    name: "Chicken Shawarma Wrap",
    smallImage: images.sweetAndSpicySmall,
    coverImage: images.sweetAndSpicy,
    deliveryPrice: "90",
    rating: 4.7,
    price: 500,
    restaurant_id: 10,
    category: "Wraps",
  },
  {
    id: 31,
    name: "Vegan Burger",
    smallImage: images.tripleChocolateSmall,
    coverImage: images.tripleChocolate,
    deliveryPrice: "60",
    rating: 4.3,
    price: 320,
    restaurant_id: 10,
    category: "Burgers",
  },
  {
    id: 32,
    name: "Tiramisu",
    smallImage: "small_tiramisu.jpg",
    coverImage: "cover_tiramisu.jpg",
    deliveryPrice: "Free",
    rating: 4.6,
    price: 400,
    restaurant_id: 10,
    category: "Desserts",
  },
  {
    id: 33,
    name: "Paneer Biryani",
    smallImage: images.veggie,
    coverImage: images.veggie,
    deliveryPrice: "140",
    rating: 4.4,
    price: 600,
    restaurant_id: 7,
    category: "Biryani",
  },
  {
    id: 34,
    name: "Almond Croissant",
    smallImage: images.sweetAndSpicySmall,
    coverImage: images.sweetAndSpicy,
    deliveryPrice: "70",
    rating: 4.4,
    price: 150,
    restaurant_id: 7,
    category: "Pastries",
  },
  {
    id: 35,
    name: "Mushroom Risotto",
    smallImage: images.tripleChocolateSmall,
    coverImage: images.tripleChocolate,
    deliveryPrice: "120",
    rating: 4.5,
    price: 500,
    restaurant_id: 7,
    category: "Indian",
  },
  {
    id: 36,
    name: "Falafel Wrap",
    smallImage: images.veggie,
    coverImage: images.veggie,
    deliveryPrice: "100",
    rating: 4.2,
    price: 400,
    restaurant_id: 9,
    category: "Wraps",
  },
  {
    id: 37,
    name: "Vanilla Latte",
    smallImage: images.veggie,
    coverImage: images.veggie,
    deliveryPrice: "Free",
    rating: 4.1,
    price: 180,
    restaurant_id: 9,
    category: "Coffee",
  },
  {
    id: 38,
    name: "Chicken Biryani",
    smallImage: images.tripleChocolateSmall,
    coverImage: images.tripleChocolate,
    deliveryPrice: "120",
    rating: 4.8,
    price: 750,
    restaurant_id: 8,
    category: "Biryani",
  },
  {
    id: 39,
    name: "Chocolate Mousse",
    smallImage: images.sweetAndSpicySmall,
    coverImage: images.sweetAndSpicy,
    deliveryPrice: "80",
    rating: 4.6,
    price: 250,
    restaurant_id: 8,
    category: "Desserts",
  },
  {
    id: 40,
    name: "Hot Chocolate",
    smallImage: images.tripleChocolateSmall,
    coverImage: images.tripleChocolate,
    deliveryPrice: "Free",
    rating: 4.0,
    price: 200,
    restaurant_id: 8,
    category: "Coffee",
  },
];

export const reduxFoodData = [
  {
    id: 1,
    name: "Greek Gyro Grill",
    typeOfCuisine: "Greek",
    timeOrdered: "2",
    totalPrice: "3000",
    totalDeliveryPrice: "500",
    smallImage: images.sweetAndSpicySmall,
  },
  {
    id: 2,
    name: "Strawberry Mojito",
    typeOfCuisine: "JUICE",
    timeOrdered: "1",
    totalPrice: "00",
    totalDeliveryPrice: "20",
    smallImage: images.veggie,
  },
  {
    id: 3,
    name: "Strawberry Mojito",
    typeOfCuisine: "JUICE",
    timeOrdered: "1",
    totalPrice: "00",
    totalDeliveryPrice: "20",
    smallImage: images.veggie,
  },
  
];
