import { userProps } from "@/types/user";
import { images } from ".";

export const user: userProps = {
  location: "",
  name: "Fussels lane, Colombo 06",
  profile: images.userProfile,
};

//TODO: restaurant is made of [menu in 3 categories cakes , pastries,sandwich,drinks, location  , open time ], each food is[ made of image , price  , rating ,delivery time , delivery price  , description , category ,its restaurant]
{
  /*
  restuarant : -name
  -rating
  -delivery time
  -logo
  -type of cuisine 
  -delivery price
  -location 
  -open time
  */
}

export const restaurants = [
  {
    id: 1,
    coverImage: images.coverImage,
    price: 800,
    name: "The Gourmet Kitchen",
    rating: 4.8,
    deliveryTime: "30 mins",
    logo: images.restaurant1,
    typeOfCuisine: "Italian",
    deliveryPrice: 3.99,
    location: "1234 Culinary Ave, Food City",
    openTime: "10:00 AM - 11:00 PM",
    distance: "2.8km",
  },
  {
    id: 2,
    coverImage: images.coverImage,
    price: 900,
    name: "Sushi Heaven",
    rating: 4.5,
    deliveryTime: "30 mins",
    logo: images.restaurant2,
    typeOfCuisine: "Japanese",
    deliveryPrice: 2.5,
    location: "5678 Ocean Blvd, Seafood Town",
    openTime: "11:00 AM - 10:00 PM",
    distance: "2.8km",
  },
  {
    id: 3,
    coverImage: images.coverImage,
    price: 900,
    name: "Taco Fiesta",
    rating: 4.7,
    deliveryTime: "25-35 mins",
    logo: images.restaurant3,
    typeOfCuisine: "Mexican",
    deliveryPrice: 3.0,
    location: "9999 Fiesta St, Taco City",
    openTime: "9:00 AM - 10:00 PM",
    distance: "2.8km",
  },
  {
    id: 4,
    coverImage: images.coverImage,
    price: 900,
    name: "Burger Barn",
    rating: 4.3,
    deliveryTime: "25 mins",
    logo: images.restaurant3,
    typeOfCuisine: "American",
    deliveryPrice: 1.99,
    location: "1010 Grill Rd, Fastfood Town",
    openTime: "11:00 AM - 12:00 AM",
    distance: "2.8km",
  },
  {
    id: 5,
    coverImage: images.coverImage,
    price: 900,
    name: "Pasta Palace",
    rating: 4.9,
    deliveryTime: "40 mins",
    logo: images.restaurant4,
    typeOfCuisine: "Italian",
    deliveryPrice: 2.99,
    location: "4321 Noodle Blvd, Pasta City",
    openTime: "12:00 PM - 10:00 PM",
    distance: "2.8km",
  },
  {
    id: 6,
    coverImage: images.coverImage,
    price: 900,
    name: "Dragon Express",
    rating: 4.4,
    deliveryTime: "30 mins",
    logo: images.restaurant5,
    typeOfCuisine: "Chinese",
    deliveryPrice: 3.5,
    location: "1238 Fortune Ln, Chinatown",
    openTime: "10:00 AM - 9:30 PM",
    distance: "2.8km",
  },
  {
    id: 7,
    coverImage: images.coverImage,
    price: 900,
    name: "Biryani House",
    rating: 4.6,
    deliveryTime: "40 mins",
    logo: images.restaurant6,
    typeOfCuisine: "Indian",
    deliveryPrice: 4.0,
    location: "123 Spice St, Curryville",
    openTime: "11:00 AM - 10:00 PM",
    distance: "2.8km",
  },
  {
    id: 8,
    coverImage: images.coverImage,
    price: 900,
    name: "Kebab King",
    rating: 4.7,
    deliveryTime: "35 mins",
    logo: images.restaurant7,
    typeOfCuisine: "Middle Eastern",
    deliveryPrice: 2.0,
    location: "5657 Grill Ave, Kabob Town",
    openTime: "12:00 PM - 11:00 PM",
    distance: "2.8km",
  },
  {
    id: 9,
    coverImage: images.coverImage,
    price: 900,
    name: "Pizza Planet",
    rating: 4.8,
    deliveryTime: "30 mins",
    logo: images.restaurant8,
    typeOfCuisine: "Pizza",
    deliveryPrice: 2.99,
    location: "5432 Slice Blvd, Pizza City",
    openTime: "11:00 AM - 1:00 AM",
    distance: "2.8km",
  },
  {
    id: 10,
    coverImage: images.coverImage,
    price: 900,
    name: "BBQ Brothers",
    rating: 4.6,
    deliveryTime: "45 mins",
    logo: images.restaurant1,
    typeOfCuisine: "Barbecue",
    deliveryPrice: 5.0,
    location: "6548 Smoke Rd, BBQ Town",
    openTime: "12:00 PM - 10:00 PM",
    distance: "2.8km",
  },
  {
    id: 11,
    coverImage: images.coverImage,
    price: 900,
    name: "Pho Paradise",
    rating: 4.9,
    deliveryTime: "40 mins",
    logo: images.restaurant2,
    typeOfCuisine: "Vietnamese",
    deliveryPrice: 3.5,
    location: "9999 Noodle St, Pho City",
    openTime: "10:00 AM - 10:00 PM",
    distance: "2.8km",
  },
  {
    id: 12,
    coverImage: images.coverImage,
    price: 900,
    name: "Burger Joint",
    rating: 4.5,
    deliveryTime: "30 mins",
    logo: images.restaurant3,
    typeOfCuisine: "American",
    deliveryPrice: 1.99,
    location: "3333 Burger Ln, Fastfood City",
    openTime: "11:00 AM - 12:00 AM",
    distance: "2.8km",
  },
  {
    id: 13,
    coverImage: images.coverImage,
    price: 900,
    name: "Dim Sum Delight",
    rating: 4.7,
    deliveryTime: "25 mins",
    logo: images.restaurant4,
    typeOfCuisine: "Chinese",
    deliveryPrice: 3.0,
    location: "1112 Dumpling Ave, Chinatown",
    openTime: "9:00 AM - 9:00 PM",
    distance: "2.8km",
  },
  {
    id: 14,
    coverImage: images.coverImage,
    price: 900,
    name: "Crepes & Co.",
    rating: 4.8,
    deliveryTime: "30 mins",
    logo: images.restaurant5,
    typeOfCuisine: "French",
    deliveryPrice: 4.0,
    location: "4445 Sweet Blvd, Dessert Town",
    openTime: "8:00 AM - 10:00 PM",

    distance: "2.8km",
  },
  {
    id: 15,
    coverImage: images.coverImage,
    price: 900,
    name: "Thai Treats",
    rating: 4.9,
    deliveryTime: "40 mins",
    logo: images.restaurant5,
    typeOfCuisine: "Thai",
    deliveryPrice: 2.99,
    location: "7890 Curry Ave, Thai City",
    openTime: "11:00 AM - 9:00 PM",

    distance: "2.8km",
  },
  {
    id: 16,
    coverImage: images.coverImage,
    price: 900,
    name: "Falafel Hub",
    rating: 4.6,
    deliveryTime: "35 mins",
    logo: images.restaurant6,
    typeOfCuisine: "Mediterranean",
    deliveryPrice: 3.5,
    location: "1010 Mezze Ln, Food City",
    openTime: "12:00 PM - 11:00 PM",
    distance: "2.8km",
  },
  {
    id: 17,
    coverImage: images.coverImage,
    price: 900,
    name: "Ramen Realm",
    rating: 4.8,
    deliveryTime: "30 mins",
    logo: images.restaurant7,
    typeOfCuisine: "Japanese",
    deliveryPrice: 3.25,
    location: "6789 Noodle St, Ramen Town",
    openTime: "11:00 AM - 11:00 PM",
    distance: "2.8km",
  },
  {
    id: 18,
    coverImage: images.coverImage,
    price: 900,
    name: "Curry House",
    rating: 4.4,
    deliveryTime: "40 mins",
    logo: images.restaurant8,
    typeOfCuisine: "Indian",
    deliveryPrice: 4.5,
    location: "2345 Spice Blvd, Curry City",
    openTime: "12:00 PM - 9:00 PM",
    distance: "2.8km",
  },
  {
    id: 19,
    coverImage: images.coverImage,
    price: 900,
    name: "Tandoori Delights",
    rating: 4.9,
    deliveryTime: "45 mins",
    logo: images.restaurant1,
    typeOfCuisine: "Indian",
    deliveryPrice: 5.0,
    location: "5556 Tandoori Ln, Spice City",
    openTime: "11:00 AM - 10:30 PM",
    distance: "2.8km",
  },
  {
    id: 20,
    coverImage: images.coverImage,
    price: 900,
    name: "Greek Gyro Grill",
    rating: 4.6,
    deliveryTime: "35 mins",
    logo: images.restaurant2,
    typeOfCuisine: "Greek",
    deliveryPrice: 3.75,
    location: "789 Gyro Blvd, Mediterranean City",
    openTime: "11:00 AM - 10:00 PM",
    distance: "2.8km",
  },
];

export const restaurantFood = [
  {
    id: 1,
    name: "Triple Chocolate Brownie",
    smallImage: "small_brownie.jpg",
    coverImage: "cover_brownie.jpg",
    deliveryPrice: "Free",
    rating: 4.3,
    price: 650,
    restaurant_id: 1,
    category: "Cakes",
  },
  {
    id: 2,
    name: "Sweet And Spicy Pastry",
    smallImage: "small_pastry.jpg",
    coverImage: "cover_pastry.jpg",
    deliveryPrice: 120,
    rating: 4.2,
    price: 400,
    restaurant_id: 1,
    category: "Pastries",
  },
  {
    id: 3,
    name: "Veggie Delight Sandwich",
    smallImage: "small_sandwich.jpg",
    coverImage: "cover_sandwich.jpg",
    deliveryPrice: "Free",
    rating: 4.5,
    price: 350,
    restaurant_id: 16,
    category: "Sandwich",
  },
  {
    id: 4,
    name: "Cheese Burst Pizza",
    smallImage: "small_pizza.jpg",
    coverImage: "cover_pizza.jpg",
    deliveryPrice: 150,
    rating: 4.7,
    price: 900,
    restaurant_id: 1,
    category: "Pizza",
  },
  {
    id: 5,
    name: "Butter Chicken Roll",
    smallImage: "small_roll.jpg",
    coverImage: "cover_roll.jpg",
    deliveryPrice: 50,
    rating: 4.4,
    price: 500,
    restaurant_id: 15,
    category: "Rolls",
  },
  {
    id: 6,
    name: "Margherita Pizza",
    smallImage: "small_margherita.jpg",
    coverImage: "cover_margherita.jpg",
    deliveryPrice: 130,
    rating: 4.6,
    price: 700,
    restaurant_id: 15,
    category: "Pizza",
  },
  {
    id: 7,
    name: "Garlic Bread",
    smallImage: "small_garlic_bread.jpg",
    coverImage: "cover_garlic_bread.jpg",
    deliveryPrice: "Free",
    rating: 4.3,
    price: 250,
    restaurant_id: 2,
    category: "Sandwich",
  },
  {
    id: 8,
    name: "Choco Lava Cake",
    smallImage: "small_choco_lava.jpg",
    coverImage: "cover_choco_lava.jpg",
    deliveryPrice: 60,
    rating: 4.8,
    price: 300,
    restaurant_id: 2,
    category: "Desserts",
  },
  {
    id: 9,
    name: "Paneer Tikka Wrap",
    smallImage: "small_paneer_wrap.jpg",
    coverImage: "cover_paneer_wrap.jpg",
    deliveryPrice: 100,
    rating: 4.5,
    price: 450,
    restaurant_id: 2,
    category: "Wraps",
  },
  {
    id: 10,
    name: "Mango Smoothie",
    smallImage: "small_mango_smoothie.jpg",
    coverImage: "cover_mango_smoothie.jpg",
    deliveryPrice: "Free",
    rating: 4.2,
    price: 150,
    restaurant_id: 14,
    category: "Drinks",
  },
  {
    id: 11,
    name: "Chicken Nuggets",
    smallImage: "small_nuggets.jpg",
    coverImage: "cover_nuggets.jpg",
    deliveryPrice: 70,
    rating: 4.4,
    price: 400,
    restaurant_id: 14,
    category: "Indian",
  },
  {
    id: 12,
    name: "Crispy Veg Burger",
    smallImage: "small_veg_burger.jpg",
    coverImage: "cover_veg_burger.jpg",
    deliveryPrice: 90,
    rating: 4.3,
    price: 200,
    restaurant_id: 3,
    category: "Burgers",
  },
  {
    id: 13,
    name: "Strawberry Milkshake",
    smallImage: "small_strawberry_shake.jpg",
    coverImage: "cover_strawberry_shake.jpg",
    deliveryPrice: 60,
    rating: 4.1,
    price: 180,
    restaurant_id: 3,
    category: "Milkshake",
  },
  {
    id: 14,
    name: "Egg Fried Rice",
    smallImage: "small_egg_fried_rice.jpg",
    coverImage: "cover_egg_fried_rice.jpg",
    deliveryPrice: 110,
    rating: 4.6,
    price: 550,
    restaurant_id: 3,
    category: "Indian",
  },
  {
    id: 15,
    name: "Tandoori Chicken",
    smallImage: "small_tandoori.jpg",
    coverImage: "cover_tandoori.jpg",
    deliveryPrice: "Free",
    rating: 4.7,
    price: 650,
    restaurant_id: 13,
    category: "Indian",
  },
  {
    id: 16,
    name: "Paneer Butter Masala",
    smallImage: "small_paneer_butter_masala.jpg",
    coverImage: "cover_paneer_butter_masala.jpg",
    deliveryPrice: 4,
    rating: 4.5,
    price: 500,
    restaurant_id: 13,
    category: "Indian",
  },
  {
    id: 17,
    name: "Cold Coffee",
    smallImage: "small_cold_coffee.jpg",
    coverImage: "cover_cold_coffee.jpg",
    deliveryPrice: "Free",
    rating: 4.0,
    price: 120,
    restaurant_id: 4,
    category: "Coffee",
  },
  {
    id: 18,
    name: "Pepperoni Pizza",
    smallImage: "small_pepperoni_pizza.jpg",
    coverImage: "cover_pepperoni_pizza.jpg",
    deliveryPrice: 160,
    rating: 4.6,
    price: 950,
    restaurant_id: 4,
    category: "Pizza",
  },
  {
    id: 19,
    name: "Vegetable Samosa",
    smallImage: "small_samosa.jpg",
    coverImage: "cover_samosa.jpg",
    deliveryPrice: "Free",
    rating: 4.3,
    price: 100,
    restaurant_id: 4,
    category: "Indian",
  },
  {
    id: 20,
    name: "Mutton Biryani",
    smallImage: "small_mutton_biryani.jpg",
    coverImage: "cover_mutton_biryani.jpg",
    deliveryPrice: 140,
    rating: 4.7,
    price: 800,
    restaurant_id: 12,
    category: "Biryani",
  },
  {
    id: 21,
    name: "Pineapple Pastry",
    smallImage: "small_pineapple_pastry.jpg",
    coverImage: "cover_pineapple_pastry.jpg",
    deliveryPrice: 70,
    rating: 4.2,
    price: 200,
    restaurant_id: 12,
    category: "Pastries",
  },
  {
    id: 22,
    name: "Chicken Caesar Wrap",
    smallImage: "small_caesar_wrap.jpg",
    coverImage: "cover_caesar_wrap.jpg",
    deliveryPrice: 90,
    rating: 4.6,
    price: 450,
    restaurant_id: 5,
    category: "Wraps",
  },
  {
    id: 23,
    name: "Iced Latte",
    smallImage: "small_iced_latte.jpg",
    coverImage: "cover_iced_latte.jpg",
    deliveryPrice: "Free",
    rating: 4.0,
    price: 200,
    restaurant_id: 5,
    category: "Coffee",
  },
  {
    id: 24,
    name: "Blueberry Muffin",
    smallImage: "small_blueberry_muffin.jpg",
    coverImage: "cover_blueberry_muffin.jpg",
    deliveryPrice: 40,
    rating: 4.4,
    price: 180,
    restaurant_id: 5,
    category: "Cakes",
  },
  {
    id: 25,
    name: "Butter Garlic Naan",
    smallImage: "small_garlic_naan.jpg",
    coverImage: "cover_garlic_naan.jpg",
    deliveryPrice: 80,
    rating: 4.5,
    price: 100,
    restaurant_id: 11,
    category: "Indian",
  },
  {
    id: 26,
    name: "Spaghetti Bolognese",
    smallImage: "small_spaghetti.jpg",
    coverImage: "cover_spaghetti.jpg",
    deliveryPrice: 120,
    rating: 4.6,
    price: 650,
    restaurant_id: 11,
    category: "Indian",
  },
  {
    id: 27,
    name: "Chicken Seekh Kebab",
    smallImage: "small_seekh_kebab.jpg",
    coverImage: "cover_seekh_kebab.jpg",
    deliveryPrice: "Free",
    rating: 4.5,
    price: 350,
    restaurant_id: 6,
    category: "Indian",
  },
  {
    id: 28,
    name: "Oreo Milkshake",
    smallImage: "small_oreo_shake.jpg",
    coverImage: "cover_oreo_shake.jpg",
    deliveryPrice: 60,
    rating: 4.7,
    price: 250,
    restaurant_id: 6,
    category: "Milkshake",
  },
  {
    id: 29,
    name: "Espresso Shot",
    smallImage: "small_espresso.jpg",
    coverImage: "cover_espresso.jpg",
    deliveryPrice: 50,
    rating: 4.1,
    price: 80,
    restaurant_id: 6,
    category: "Coffee",
  },
  {
    id: 30,
    name: "Chicken Shawarma Wrap",
    smallImage: "small_shawarma_wrap.jpg",
    coverImage: "cover_shawarma_wrap.jpg",
    deliveryPrice: 90,
    rating: 4.7,
    price: 500,
    restaurant_id: 10,
    category: "Wraps",
  },
  {
    id: 31,
    name: "Vegan Burger",
    smallImage: "small_vegan_burger.jpg",
    coverImage: "cover_vegan_burger.jpg",
    deliveryPrice: 60,
    rating: 4.3,
    price: 320,
    restaurant_id: 10,
    category: "Burgers",
  },
  {
    id: 32,
    name: "Tiramisu",
    smallImage: "small_tiramisu.jpg",
    coverImage: "cover_tiramisu.jpg",
    deliveryPrice: "Free",
    rating: 4.6,
    price: 400,
    restaurant_id: 10,
    category: "Desserts",
  },
  {
    id: 33,
    name: "Paneer Biryani",
    smallImage: "small_paneer_biryani.jpg",
    coverImage: "cover_paneer_biryani.jpg",
    deliveryPrice: 140,
    rating: 4.4,
    price: 600,
    restaurant_id: 7,
    category: "Biryani",
  },
  {
    id: 34,
    name: "Almond Croissant",
    smallImage: "small_almond_croissant.jpg",
    coverImage: "cover_almond_croissant.jpg",
    deliveryPrice: 70,
    rating: 4.4,
    price: 150,
    restaurant_id: 7,
    category: "Pastries",
  },
  {
    id: 35,
    name: "Mushroom Risotto",
    smallImage: "small_mushroom_risotto.jpg",
    coverImage: "cover_mushroom_risotto.jpg",
    deliveryPrice: 120,
    rating: 4.5,
    price: 500,
    restaurant_id: 7,
    category: "Indian",
  },
  {
    id: 36,
    name: "Falafel Wrap",
    smallImage: "small_falafel_wrap.jpg",
    coverImage: "cover_falafel_wrap.jpg",
    deliveryPrice: 100,
    rating: 4.2,
    price: 400,
    restaurant_id: 9,
    category: "Wraps",
  },
  {
    id: 37,
    name: "Vanilla Latte",
    smallImage: "small_vanilla_latte.jpg",
    coverImage: "cover_vanilla_latte.jpg",
    deliveryPrice: "Free",
    rating: 4.1,
    price: 180,
    restaurant_id: 9,
    category: "Coffee",
  },
  {
    id: 38,
    name: "Chicken Biryani",
    smallImage: "small_chicken_biryani.jpg",
    coverImage: "cover_chicken_biryani.jpg",
    deliveryPrice: 120,
    rating: 4.8,
    price: 750,
    restaurant_id: 8,
    category: "Biryani",
  },
  {
    id: 39,
    name: "Chocolate Mousse",
    smallImage: "small_choco_mousse.jpg",
    coverImage: "cover_choco_mousse.jpg",
    deliveryPrice: 80,
    rating: 4.6,
    price: 250,
    restaurant_id: 8,
    category: "Desserts",
  },
  {
    id: 40,
    name: "Hot Chocolate",
    smallImage: "small_hot_choco.jpg",
    coverImage: "cover_hot_choco.jpg",
    deliveryPrice: "Free",
    rating: 4.0,
    price: 200,
    restaurant_id: 8,
    category: "Coffee",
  },
];
