import { userProps } from "@/types/user";
import { images } from ".";

export const user: userProps = {
  location: "",
  name: "Fussels lane, Colombo 06",
  profile: images.userProfile,
};

//TODO: restaurant is made of [menu in 3 categories cakes , pastries,sandwich,drinks, location  , open time ], each food is[ made of image , price  , rating ,delivery time , delivery price  , description , category ,its restaurant]
{
  /*
  restuarant : -name
  -rating
  -delivery time
  -logo
  -type of cuisine 
  -delivery price
  -location 
  -open time
  */
}

export const restaurants = [
  {
    rs: 800,
    name: "The Gourmet Kitchen",
    rating: 4.8,
    deliveryTime: "30-40 mins",
    logo: images.restaurant1,
    typeOfCuisine: "Italian",
    deliveryPrice: 3.99,
    location: "1234 Culinary Ave, Food City",
    openTime: "10:00 AM - 11:00 PM",
  },
  {
    rs: 900,
    name: "Sushi Heaven",
    rating: 4.5,
    deliveryTime: "20-30 mins",
    logo:images.restaurant2,
    typeOfCuisine: "Japanese",
    deliveryPrice: 2.5,
    location: "5678 Ocean Blvd, Seafood Town",
    openTime: "11:00 AM - 10:00 PM",
  },
  {
    rs: 900,
    name: "Taco Fiesta",
    rating: 4.7,
    deliveryTime: "25-35 mins",
    logo: images.restaurant3,
    typeOfCuisine: "Mexican",
    deliveryPrice: 3.0,
    location: "9999 Fiesta St, Taco City",
    openTime: "9:00 AM - 10:00 PM",
  },
  {
    rs: 900,
    name: "Burger Barn",
    rating: 4.3,
    deliveryTime: "15-25 mins",
    logo: images.restaurant3,
    typeOfCuisine: "American",
    deliveryPrice: 1.99,
    location: "1010 Grill Rd, Fastfood Town",
    openTime: "11:00 AM - 12:00 AM",
  },
  {
    rs: 900,
    name: "Pasta Palace",
    rating: 4.9,
    deliveryTime: "30-40 mins",
    logo: images.restaurant4,
    typeOfCuisine: "Italian",
    deliveryPrice: 2.99,
    location: "4321 Noodle Blvd, Pasta City",
    openTime: "12:00 PM - 10:00 PM",
  },
  {
    rs: 900,
    name: "Dragon Express",
    rating: 4.4,
    deliveryTime: "20-30 mins",
    logo: images.restaurant5,
    typeOfCuisine: "Chinese",
    deliveryPrice: 3.5,
    location: "1238 Fortune Ln, Chinatown",
    openTime: "10:00 AM - 9:30 PM",
  },
  {
    rs: 900,
    name: "Biryani House",
    rating: 4.6,
    deliveryTime: "30-40 mins",
    logo: images.restaurant6,
    typeOfCuisine: "Indian",
    deliveryPrice: 4.0,
    location: "123 Spice St, Curryville",
    openTime: "11:00 AM - 10:00 PM",
  },
  {
    rs: 900,
    name: "Kebab King",
    rating: 4.7,
    deliveryTime: "25-35 mins",
    logo: images.restaurant7,
    typeOfCuisine: "Middle Eastern",
    deliveryPrice: 2.0,
    location: "5657 Grill Ave, Kabob Town",
    openTime: "12:00 PM - 11:00 PM",
  },
  {
    rs: 900,
    name: "Pizza Planet",
    rating: 4.8,
    deliveryTime: "20-30 mins",
    logo: images.restaurant8,
    typeOfCuisine: "Pizza",
    deliveryPrice: 2.99,
    location: "5432 Slice Blvd, Pizza City",
    openTime: "11:00 AM - 1:00 AM",
  },
  {
    rs: 900,
    name: "BBQ Brothers",
    rating: 4.6,
    deliveryTime: "35-45 mins",
    logo: images.restaurant1,
    typeOfCuisine: "Barbecue",
    deliveryPrice: 5.0,
    location: "6548 Smoke Rd, BBQ Town",
    openTime: "12:00 PM - 10:00 PM",
  },
  {
    rs: 900,
    name: "Pho Paradise",
    rating: 4.9,
    deliveryTime: "30-40 mins",
    logo: images.restaurant2,
    typeOfCuisine: "Vietnamese",
    deliveryPrice: 3.5,
    location: "9999 Noodle St, Pho City",
    openTime: "10:00 AM - 10:00 PM",
  },
  {
    rs: 900,
    name: "Burger Joint",
    rating: 4.5,
    deliveryTime: "20-30 mins",
    logo: images.restaurant3,
    typeOfCuisine: "American",
    deliveryPrice: 1.99,
    location: "3333 Burger Ln, Fastfood City",
    openTime: "11:00 AM - 12:00 AM",
  },
  {
    rs: 900,
    name: "Dim Sum Delight",
    rating: 4.7,
    deliveryTime: "15-25 mins",
    logo: images.restaurant4,
    typeOfCuisine: "Chinese",
    deliveryPrice: 3.0,
    location: "1112 Dumpling Ave, Chinatown",
    openTime: "9:00 AM - 9:00 PM",
  },
  {
    rs: 900,
    name: "Crepes & Co.",
    rating: 4.8,
    deliveryTime: "20-30 mins",
    logo: images.restaurant5,
    typeOfCuisine: "French",
    deliveryPrice: 4.0,
    location: "4445 Sweet Blvd, Dessert Town",
    openTime: "8:00 AM - 10:00 PM",
  },
  {
    rs: 900,
    name: "Thai Treats",
    rating: 4.9,
    deliveryTime: "30-40 mins",
    logo: images.restaurant5,
    typeOfCuisine: "Thai",
    deliveryPrice: 2.99,
    location: "7890 Curry Ave, Thai City",
    openTime: "11:00 AM - 9:00 PM",
  },
  {
    rs: 900,
    name: "Falafel Hub",
    rating: 4.6,
    deliveryTime: "25-35 mins",
    logo: images.restaurant6,
    typeOfCuisine: "Mediterranean",
    deliveryPrice: 3.5,
    location: "1010 Mezze Ln, Food City",
    openTime: "12:00 PM - 11:00 PM",
  },
  {
    rs: 900,
    name: "Ramen Realm",
    rating: 4.8,
    deliveryTime: "20-30 mins",
    logo: images.restaurant7,
    typeOfCuisine: "Japanese",
    deliveryPrice: 3.25,
    location: "6789 Noodle St, Ramen Town",
    openTime: "11:00 AM - 11:00 PM",
  },
  {
    rs: 900,
    name: "Curry House",
    rating: 4.4,
    deliveryTime: "30-40 mins",
    logo: images.restaurant8,
    typeOfCuisine: "Indian",
    deliveryPrice: 4.5,
    location: "2345 Spice Blvd, Curry City",
    openTime: "12:00 PM - 9:00 PM",
  },
  {
    rs: 900,
    name: "Tandoori Delights",
    rating: 4.9,
    deliveryTime: "35-45 mins",
    logo: images.restaurant1,
    typeOfCuisine: "Indian",
    deliveryPrice: 5.0,
    location: "5556 Tandoori Ln, Spice City",
    openTime: "11:00 AM - 10:30 PM",
  },
  {
    rs: 900,
    name: "Greek Gyro Grill",
    rating: 4.6,
    deliveryTime: "25-35 mins",
    logo: images.restaurant2,
    typeOfCuisine: "Greek",
    deliveryPrice: 3.75,
    location: "789 Gyro Blvd, Mediterranean City",
    openTime: "11:00 AM - 10:00 PM",
  },
];
